### ISSUE TITLE
celery执行任务结果无法保存

### ISSUE THREAD

**Issue by shadowzey** [sdg32/flask-celery3-boilerplate#1]
worker 启动命令: celery -A app.celery worker --loglevel=info
beat 启动命令: celery -A app.celery beat --loglevel=info

执行celery.backend_cleanup任务时worker报错
worker 报错信息如下:
![报错截图](http://oe5x4zsbj.bkt.clouddn.com/2017-06-01%2017-58-59%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)

**Comment by sdg32** [comment]
能提供你的运行环境吗？我这里测试的没有问题，Windows10 + Python3.6 + Celery3.1.25：
![celery3](https://cloud.githubusercontent.com/assets/13184041/26753655/a2c1d7d6-489d-11e7-9b3d-79c9f48ea56a.png)

**Comment by shadowzey** [comment]
Ubuntu 16.10 + python3.6.0 + Celery3.1.25

应该是下面代码的celery_state 没有正确传递

```
#app/schedule/backends.py

from app import db
from app import celery_state
from .models import TaskResult

class DatabaseBackend(BaseBackend):

    subpolling_interval = 0.5

    @staticmethod
    @retry
    def _store_result(task_id, result, status, traceback=None, request=None):
        task = celery_state.tasks[task_id]
```

**Comment by sdg32** [comment]
特地安装了个 Ubuntu 试了试，最后发现原因是 Windows 和 Linux 开启新线程的方式不同，Windows 使用 `spawn` 而 Linux 使用 `fork`，导致在 Linux 上 worker 只拿到了 `celery_state` 的初始值而没有运行监控进程。
目前解决办法是在 worker 进程初始化时，运行监控进程：[Fixed celery state error on linux platform](https://github.com/sdg32/flask-celery3-boilerplate/commit/e8d2bca7dec3ba1ce33f8ce0087d4c3d9ee5423f)。

**Comment by shadowzey** [comment]
测试已无问题，谢谢
